sifenasifena:
    resource: "@sifenasifenaBundle/Resources/config/routing.yml"
    prefix:   /
    
login:
    path:     /login 
    defaults: { _controller: sifenasifenaBundle:Acesso:login }
login_check:
    path: /login_check    

