security:
    encoders:
            sifena\sifenaBundle\Entity\Utilizador: 
                algorithm: sha1
                iterations: 1
                encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: sifena\sifenaBundle\Entity\Utilizador , property: username }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: home_redirect
                
            logout:
                path:  /logout
                target: /login
        login_firewall:
            pattern: ^/login$
            anonymous:         
    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/, roles: ROLE_USER, requires_channel: http }
        - { path: ^/admin/, roles: ROLE_ADMIN, requires_channel: http }
        - { path: ^/admin$, roles: ROLE_ADMIN, requires_channel: http }
       