documento:
    path:     /
    defaults: { _controller: "sifenasifenaBundle:Documento:index" }

documento_show:
    path:     /{id}/show
    defaults: { _controller: "sifenasifenaBundle:Documento:show" }

documento_new:
    path:     /new
    defaults: { _controller: "sifenasifenaBundle:Documento:new" }

documento_create:
    path:     /create
    defaults: { _controller: "sifenasifenaBundle:Documento:create" }
    requirements: { _method: post }

documento_edit:
    path:     /{id}/edit
    defaults: { _controller: "sifenasifenaBundle:Documento:edit" }

documento_update:
    path:     /{id}/update
    defaults: { _controller: "sifenasifenaBundle:Documento:update" }
    requirements: { _method: post|put }

documento_delete:
    path:     /{id}/delete
    defaults: { _controller: "sifenasifenaBundle:Documento:delete" }
    requirements: { _method: post|delete }
