tipocontrato:
    path:     /
    defaults: { _controller: "sifenasifenaBundle:TipoContrato:index" }

tipocontrato_show:
    path:     /{id}/show
    defaults: { _controller: "sifenasifenaBundle:TipoContrato:show" }

tipocontrato_new:
    path:     /new
    defaults: { _controller: "sifenasifenaBundle:TipoContrato:new" }

tipocontrato_create:
    path:     /create
    defaults: { _controller: "sifenasifenaBundle:TipoContrato:create" }
    requirements: { _method: post }

tipocontrato_edit:
    path:     /{id}/edit
    defaults: { _controller: "sifenasifenaBundle:TipoContrato:edit" }

tipocontrato_update:
    path:     /{id}/update
    defaults: { _controller: "sifenasifenaBundle:TipoContrato:update" }
    requirements: { _method: post|put }

tipocontrato_delete:
    path:     /{id}/delete
    defaults: { _controller: "sifenasifenaBundle:TipoContrato:delete" }
    requirements: { _method: post|delete }
