<?php

namespace Proxies\__CG__\sifena\sifenaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Trabalhador extends \sifena\sifenaBundle\Entity\Trabalhador implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'grauAcademico', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'numeroInterno', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'numeroConta', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'iban', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'pessoa', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'sector', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'profissao', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'categoria', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'instituicaoBancaria');
        }

        return array('__isInitialized__', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'grauAcademico', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'numeroInterno', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'numeroConta', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'iban', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'pessoa', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'sector', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'profissao', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'categoria', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Trabalhador' . "\0" . 'instituicaoBancaria');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Trabalhador $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setGrauAcademico($grauAcademico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrauAcademico', array($grauAcademico));

        return parent::setGrauAcademico($grauAcademico);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrauAcademico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrauAcademico', array());

        return parent::getGrauAcademico();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroInterno($numeroInterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroInterno', array($numeroInterno));

        return parent::setNumeroInterno($numeroInterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroInterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroInterno', array());

        return parent::getNumeroInterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroConta($numeroConta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroConta', array($numeroConta));

        return parent::setNumeroConta($numeroConta);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroConta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroConta', array());

        return parent::getNumeroConta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban($iban)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban', array($iban));

        return parent::setIban($iban);
    }

    /**
     * {@inheritDoc}
     */
    public function getIban()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban', array());

        return parent::getIban();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoa(\sifena\sifenaBundle\Entity\Pessoa $pessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoa', array($pessoa));

        return parent::setPessoa($pessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoa', array());

        return parent::getPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setSector(\sifena\sifenaBundle\Entity\Sector $sector = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSector', array($sector));

        return parent::setSector($sector);
    }

    /**
     * {@inheritDoc}
     */
    public function getSector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSector', array());

        return parent::getSector();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfissao(\sifena\sifenaBundle\Entity\Profissao $profissao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfissao', array($profissao));

        return parent::setProfissao($profissao);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfissao', array());

        return parent::getProfissao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(\sifena\sifenaBundle\Entity\Categoria $categoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', array($categoria));

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', array());

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstituicaoBancaria(\sifena\sifenaBundle\Entity\InstituicaoBancaria $instituicaoBancaria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstituicaoBancaria', array($instituicaoBancaria));

        return parent::setInstituicaoBancaria($instituicaoBancaria);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstituicaoBancaria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstituicaoBancaria', array());

        return parent::getInstituicaoBancaria();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
