<?php

namespace Proxies\__CG__\sifena\sifenaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Candidato extends \sifena\sifenaBundle\Entity\Candidato implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'dataCandidatura', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'anexo', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'observacao', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'estado', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'pessoa', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'formacao');
        }

        return array('__isInitialized__', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'dataCandidatura', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'anexo', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'observacao', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'estado', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'pessoa', '' . "\0" . 'sifena\\sifenaBundle\\Entity\\Candidato' . "\0" . 'formacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Candidato $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDataCandidatura($dataCandidatura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCandidatura', array($dataCandidatura));

        return parent::setDataCandidatura($dataCandidatura);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCandidatura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCandidatura', array());

        return parent::getDataCandidatura();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnexo($anexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnexo', array($anexo));

        return parent::setAnexo($anexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnexo', array());

        return parent::getAnexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', array($observacao));

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', array());

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoa(\sifena\sifenaBundle\Entity\Pessoa $pessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoa', array($pessoa));

        return parent::setPessoa($pessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoa', array());

        return parent::getPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormacao(\sifena\sifenaBundle\Entity\Formacao $formacao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormacao', array($formacao));

        return parent::setFormacao($formacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormacao', array());

        return parent::getFormacao();
    }

}
